import { escapeHtml as e, field } from './ui.js';
import { clubHistoryFields, clubSimulationFields } from './history-ui.js';

export function clubForm(club, document) {
  const members = document.memberships.filter(member => member.clubId === club.id);
  const players = members.map(member => document.players.find(player => player.id === member.playerId));
  const goalkeepers = players.filter(player => player?.naturalPositions.includes('GK')).length;
  const path = `clubs[${document.clubs.indexOf(club)}]`;
  return `<div class="detail-heading"><div><p class="eyebrow">FICHA DO CLUBE</p><h2 id="detail-title" tabindex="-1">${e(club.name || 'Clube sem nome')}</h2><p class="detail-subtitle">${members.length} jogadores no elenco</p></div><svg class="club-outline" viewBox="0 0 56 66" aria-hidden="true"><path d="M5 5h46v32L28 60 5 37Z" fill="none" stroke="currentColor" stroke-width="2"/><path d="M17 22h22M17 30h22M28 22v22" fill="none" stroke="currentColor" stroke-width="2"/></svg></div><form id="record-form" novalidate><fieldset id="record-fields"><legend class="sr-only">Editar ${e(club.name)}</legend><div class="section-label"><h3>Identificação</h3><p>O nome aparece na seleção de times e na partida.</p></div>${field({ id: 'club-name', label: 'Nome do clube', value: club.name, path: `clubs[${document.clubs.indexOf(club)}].name` })}${clubHistoryFields(club, document, path)}<div class="roster-summary"><div><span class="summary-number">${members.length}</span><span>jogadores</span></div><div><span class="summary-number">${goalkeepers}</span><span>goleiros naturais</span></div><button type="button" class="button button-outline" id="view-roster">Ver elenco <span aria-hidden="true">→</span></button></div><div class="notice"><strong>Escudo, uniforme e formação</strong><p>Estes recursos ainda são definidos no Unity. Um clube novo utiliza os visuais padrão do jogo até receber recursos próprios.</p></div><p class="form-note">Para disputar um amistoso, o clube precisa de um goleiro natural e dez jogadores de linha aptos à escalação.</p>${clubSimulationFields(club, document, path)}</fieldset></form><div class="detail-footer"><details class="record-id"><summary>Identificador permanente</summary><code>${e(club.id)}</code><p>Renomear o clube preserva os vínculos do elenco e dos recursos visuais.</p></details><button class="button button-ghost-danger" id="delete-record">Excluir clube</button></div>`;
}
