import { escapeHtml as e, field, select } from './ui.js';
import { roundCount, playoffLabels } from './competition-rules.js';
import { competitionMetadataFields } from './competition-metadata-ui.js';

const editable = (html, path) => html.replace(/<(input|select) /, `<$1 data-edition-path="${e(path)}" `);
const input = (options, property) => editable(field(options), property);
const picker = (options, property) => editable(select(options), property);
const footer = (record, label) => `<div class="detail-footer"><details class="record-id"><summary>Identificador permanente</summary><code>${e(record.id)}</code><p>Renomear preserva as referências. Temporadas salvas continuam usando sua base original.</p></details><button class="button button-ghost-danger" id="delete-record">Excluir ${label}</button></div>`;

export function competitionForm(competition, document) {
  const editions = document.competitionEditions.filter(edition => edition.competitionId === competition.id);
  const path = `competitions[${document.competitions.indexOf(competition)}]`;
  return `<div class="detail-heading"><div><p class="eyebrow">CAMPEONATO</p><h2 id="detail-title" tabindex="-1">${e(competition.name || 'Campeonato sem nome')}</h2><p class="detail-subtitle">${editions.length} edições cadastradas</p></div></div><form id="record-form" novalidate><fieldset id="record-fields"><legend class="sr-only">Editar campeonato</legend>${field({ id: 'competition-name', label: 'Nome do campeonato', value: competition.name, property: 'name', path: `${path}.name`, maxLength: 100 })}${competitionMetadataFields(competition, document)}<div class="notice"><strong>Um campeonato, várias edições</strong><p>O campeonato identifica a competição. Cada edição define seus clubes, regulamento e datas; por exemplo, Paulista 2026 e Paulista 2027.</p></div><div class="competition-edition-links">${editions.map(edition => `<button type="button" class="button button-outline" data-open-edition="${e(edition.id)}">${e(edition.name)} →</button>`).join('')}</div><button type="button" class="button button-primary" id="add-competition-edition">Adicionar edição</button></fieldset></form>${footer(competition, 'campeonato')}`;
}

export function editionForm(edition, document, selectedRound = 1) {
  const path = `competitionEditions[${document.competitionEditions.indexOf(edition)}]`;
  const paulista = edition.rules.type === 'paulista-2026';
  const clubs = [...document.clubs].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'));
  const options = [{ value: 'round-robin', label: 'Pontos corridos — um ou dois turnos' }];
  if (document.schemaVersion >= 4) options.push({ value: 'paulista-2026', label: 'Formato Paulista 2026 — 16 clubes e mata-mata' });
  return `<div class="detail-heading"><div><p class="eyebrow">EDIÇÃO DO CAMPEONATO</p><h2 id="detail-title" tabindex="-1">${e(edition.name || 'Edição sem nome')}</h2><p class="detail-subtitle">${edition.participantClubIds.length} clubes · ${paulista ? '8 rodadas + mata-mata' : `${Math.max(0, roundCount(edition))} rodadas`}</p></div></div><form id="record-form" novalidate><fieldset id="record-fields"><legend class="sr-only">Editar edição</legend><div class="form-grid">${field({ id: 'edition-name', label: 'Nome da edição', value: edition.name, property: 'name', path: `${path}.name`, maxLength: 100 })}${picker({ id: 'edition-competition', label: 'Campeonato', value: edition.competitionId, path: `${path}.competitionId`, options: document.competitions.map(item => ({ value: item.id, label: item.name })) }, 'competitionId')}</div>
    <div class="section-label section-separated"><h3>Participantes</h3><p>Escolha os clubes desta edição. Remover um participante não apaga seus jogos; ajuste o calendário antes de salvar.</p></div>
    <fieldset class="participant-field" id="edition-participants" data-path="${path}.participantClubIds" tabindex="-1" aria-describedby="edition-participants-hint edition-participants-error"><legend>Clubes participantes</legend><div class="participant-options">${clubs.map(club => `<label class="participant-option"><input type="checkbox" name="participant" value="${e(club.id)}"${edition.participantClubIds.includes(club.id) ? ' checked' : ''}><span>${e(club.name)}</span></label>`).join('')}</div><small class="field-hint" id="edition-participants-hint">${paulista ? 'Exatamente 16 clubes.' : 'De 2 a 64 clubes. A ordem de inclusão determina o calendário gerado do turno.'}</small><small class="field-error" id="edition-participants-error"></small></fieldset>
    <div class="section-label section-separated"><h3>Regulamento</h3><p>Escolha um dos formatos implementados no jogo. Editar esta base afeta novas temporadas; saves existentes preservam suas regras.</p></div>${select({ id: 'edition-format', label: 'Formato', value: edition.rules.type, path: `${path}.rules.type`, options })}${document.schemaVersion >= 6 ? select({ id: 'edition-format-ref', label: 'Converter para formato reutilizável', value: '', options: [{ value: '', label: 'Manter regulamento legado' }, ...(document.competitionFormats || []).map(f => ({ value: f.id, label: f.name }))], hint: 'A conversão pede confirmação e substitui os calendários. Os participantes e o ID da edição são preservados.' }) : ''}
    ${paulista ? '<div class="notice"><strong>Formato Paulista 2026</strong><p>Primeira fase com oito adversários e quatro mandos por clube. Oito classificados; quartas e semifinais em jogo único, com desempate por pênaltis. Final de ida e volta. Semifinais e mando da final usam a campanha acumulada. Os dois últimos da primeira fase são rebaixados na classificação da edição.</p><p>Pontos: 3 por vitória, 1 por empate e 0 por derrota. Desempates: vitórias, saldo, gols, menos cartões vermelhos, menos amarelos e sorteio. Estes parâmetros são fixos neste formato.</p></div>' : `${picker({ id: 'edition-legs', label: 'Turnos', value: String(edition.rules.legs), path: `${path}.rules.legs`, options: [{ value: '1', label: 'Um turno' }, { value: '2', label: 'Ida e volta' }] }, 'rules.legs')}<div class="form-grid points-grid" id="edition-points" data-path="${path}.rules.points" tabindex="-1" aria-describedby="edition-points-error">${[['win', 'Vitória'], ['draw', 'Empate'], ['loss', 'Derrota']].map(([key, label]) => input({ id: `edition-points-${key}`, label: `Pontos por ${label.toLocaleLowerCase('pt-BR')}`, value: edition.rules.points[key], type: 'number', min: 0, max: 100, path: `${path}.rules.points.${key}` }, `rules.points.${key}`)).join('')}<small class="field-error" id="edition-points-error"></small></div><p class="form-note">Desempates: vitórias, saldo de gols e gols marcados. Empate completo mantém posição compartilhada.</p>`}
    <div class="section-label section-separated"><h3>Calendário da primeira fase</h3><p>${paulista ? 'A data por rodada abre a janela dos jogos; cada confronto tem seu próprio dia e mando.' : 'Cada rodada ocorre na data indicada. O jogo gera os confrontos entre os participantes.'}</p></div>
    <div id="edition-dates" data-path="${path}.roundDates" tabindex="-1" aria-describedby="edition-dates-error"><button type="button" class="button button-outline" id="generate-round-dates">Gerar datas por intervalo</button><small class="field-error" id="edition-dates-error"></small><div class="form-grid round-dates">${Array.from({ length: Math.min(128, Math.max(edition.roundDates.length, roundCount(edition), 0)) }, (_, i) => input({ id: `round-date-${i}`, label: `Rodada ${i + 1}`, value: edition.roundDates[i] || '', maxLength: 10, path: `${path}.roundDates[${i}]`, hint: 'AAAA-MM-DD' }, `roundDates[${i}]`)).join('')}</div></div>
    ${paulista ? playoffFields(edition, path) + fixtureFields(edition, document, path, selectedRound) : ''}
    <p class="form-note">Salvar publica o calendário para novas partidas e carreiras. Resultados e evolução diária pertencem ao save do jogo.</p></fieldset></form>${footer(edition, 'edição')}`;
}

function playoffFields(edition, path) {
  return `<div class="section-label section-separated"><h3>Calendário do mata-mata</h3><p>O ranking das semifinais considera a campanha até as quartas. As datas pertencem às posições da chave; os clubes são definidos durante a temporada.</p></div><div class="form-grid" id="edition-playoffs" data-path="${path}.playoffDates" tabindex="-1" aria-describedby="edition-playoffs-error">${playoffLabels.map((label, index) => input({ id: `playoff-date-${index}`, label, value: edition.playoffDates?.[index] || '', path: `${path}.playoffDates[${index}]`, maxLength: 10, hint: 'AAAA-MM-DD' }, `playoffDates[${index}]`)).join('')}<small class="field-error" id="edition-playoffs-error"></small></div>`;
}

function fixtureFields(edition, document, path, selectedRound) {
  const fixtures = edition.authoredFixtures || [];
  const clubOptions = [{ value: '', label: 'Selecione o clube' }, ...edition.participantClubIds.map(id => ({ value: id, label: document.clubs.find(club => club.id === id)?.name || id }))];
  const shown = fixtures.filter(fixture => fixture.round === selectedRound);
  return `<div class="section-label section-separated"><h3>Confrontos autorados</h3><p>${fixtures.length} de 64 jogos cadastrados. Cada clube precisa de oito adversários distintos, quatro jogos em casa e quatro fora.</p></div><div id="edition-fixtures" data-path="${path}.authoredFixtures" tabindex="-1" aria-describedby="edition-fixtures-error"><small class="field-error" id="edition-fixtures-error"></small><div class="fixture-toolbar">${select({ id: 'fixture-round-filter', label: 'Ver rodada', value: String(selectedRound), options: Array.from({ length: 8 }, (_, index) => ({ value: String(index + 1), label: `Rodada ${index + 1}` })) })}<button type="button" class="button button-outline" id="add-authored-fixture"${fixtures.length >= 64 ? ' disabled' : ''}>Adicionar jogo</button></div>${fixtures.length >= 64 ? '<p class="form-note">O calendário já tem 64 jogos. Edite um confronto existente ou remova um jogo antes de adicionar outro.</p>' : ''}<p class="list-summary">${shown.length} jogos nesta rodada</p><div class="authored-fixtures">${shown.length ? shown.map(fixture => {
    const index = fixtures.indexOf(fixture); const fp = `${path}.authoredFixtures[${index}]`; const prop = `authoredFixtures[${index}]`;
    return `<section class="fixture-card" aria-label="Jogo ${index + 1}"><div class="fixture-card-heading"><h4>Jogo ${index + 1}</h4><button type="button" class="button button-ghost-danger" data-delete-fixture="${e(fixture.id)}">Remover jogo ${index + 1}</button></div><div class="form-grid">${picker({ id: `fixture-${index}-home`, label: 'Mandante', value: fixture.homeClubId, path: `${fp}.homeClubId`, options: clubOptions }, `${prop}.homeClubId`)}${picker({ id: `fixture-${index}-away`, label: 'Visitante', value: fixture.awayClubId, path: `${fp}.awayClubId`, options: clubOptions }, `${prop}.awayClubId`)}${input({ id: `fixture-${index}-date`, label: 'Data do jogo', value: fixture.date, path: `${fp}.date`, hint: 'AAAA-MM-DD', maxLength: 10 }, `${prop}.date`)}${picker({ id: `fixture-${index}-round`, label: 'Rodada do jogo', value: String(fixture.round), path: `${fp}.round`, options: Array.from({ length: 8 }, (_, i) => ({ value: String(i + 1), label: `Rodada ${i + 1}` })) }, `${prop}.round`)}</div>${picker({ id: `fixture-${index}-stadium`, label: 'Estádio deste jogo', value: fixture.stadiumId || '', path: `${fp}.stadiumId`, hint: 'Vazio usa o estádio principal do mandante. Uma exceção não altera o cadastro do clube nem troca o cenário 3D.', options: [{ value: '', label: 'Estádio principal do mandante' }, ...(document.stadiums || []).map(stadium => ({ value: stadium.id, label: `${stadium.name} · ${stadium.city}` }))] }, `${prop}.stadiumId`)}</section>`;
  }).join('') : '<div class="empty-list"><strong>Nenhum jogo nesta rodada</strong><p>Adicione os confrontos ou altere a rodada de um jogo existente.</p></div>'}</div></div>`;
}
