import { escapeHtml as e, field, select, textarea } from './ui.js';
import { countryOptions, countryName, displayDate, rosterScopeLabel, hasHistory } from './history-model.js';

export function countryField(document, { id, value, path, property = 'countryCode', optional = false, label = 'País' }) {
  return select({ id, label, value: value || '', path, property, optional, options: [{ value: '', label: optional ? 'Não informado' : 'Selecione o país' }, ...countryOptions(document)] });
}

export function referenceStrip(document) {
  if (!hasHistory(document)) return '';
  const snapshot = document.snapshot;
  return `<section class="reference-strip" aria-label="Referência histórica da base"><div><span class="eyebrow">RETRATO DA BASE</span><strong>${e(snapshot?.label || 'Referência sem título')}</strong></div><div class="reference-date">${e(displayDate(snapshot?.date))}<span>${e(rosterScopeLabel(snapshot?.rosterScope))}</span></div><button class="text-button" id="open-reference">Ver referência e fontes →</button></section>`;
}

export function playerHistoryFields(player, document, path) {
  if (!hasHistory(document)) return '';
  return `<div class="section-label"><h3>Dados pessoais</h3><p>Campos opcionais. Deixe vazio o que ainda não foi confirmado nas fontes.</p></div><div class="form-grid">${field({ id: 'player-nickname', label: 'Apelido', value: player.nickname, property: 'nickname', optional: true, maxLength: 100, path: `${path}.nickname`, hint: 'Exibido nos menus e na partida; vazio usa o nome cadastrado.' })}${field({ id: 'player-full-name', label: 'Nome completo', value: player.fullName, property: 'fullName', optional: true, maxLength: 200, path: `${path}.fullName` })}${countryField(document, { id: 'player-nationality', label: 'Nacionalidade', value: player.nationalityCode, property: 'nationalityCode', optional: true, path: `${path}.nationalityCode` })}${field({ id: 'player-birth-date', label: 'Data de nascimento', value: player.birthDate, property: 'birthDate', optional: true, maxLength: 10, path: `${path}.birthDate`, hint: 'AAAA-MM-DD. Até a data de referência da base.' })}${select({ id: 'player-preferred-foot', label: 'Pé preferido', value: player.preferredFoot || '', property: 'preferredFoot', optional: true, path: `${path}.preferredFoot`, options: [{ value: '', label: 'Não informado' }, { value: 'right', label: 'Direito' }, { value: 'left', label: 'Esquerdo' }, { value: 'both', label: 'Ambos' }] })}</div>`;
}

export function notesField(record, prefix, path) {
  return textarea({ id: `${prefix}-notes`, label: 'Notas de pesquisa', value: record.notes, property: 'notes', optional: true, path: `${path}.notes`, hint: 'Registre dúvidas, contexto ou fontes específicas. Até 4.000 caracteres.' });
}

export function clubHistoryFields(club, document, path) {
  if (!hasHistory(document)) return '';
  return `<div class="form-grid">${field({ id: 'club-official-name', label: 'Nome oficial', value: club.officialName, property: 'officialName', optional: true, maxLength: 200, path: `${path}.officialName` })}${field({ id: 'club-short-name', label: 'Nome abreviado', value: club.shortName, property: 'shortName', optional: true, maxLength: 100, path: `${path}.shortName` })}${countryField(document, { id: 'club-country', value: club.countryCode, path: `${path}.countryCode` })}${document.schemaVersion >= 6 ? field({ id: 'club-state', label: 'Código do estado / região', value: club.stateCode, property: 'stateCode', optional: true, maxLength: 8, path: `${path}.stateCode`, hint: 'Ex.: SP. De 1 a 8 letras maiúsculas ou dígitos; usado na elegibilidade dos campeonatos. Não é inferido pela cidade.' }) : ''}${field({ id: 'club-city', label: 'Cidade', value: club.city, property: 'city', maxLength: 100, path: `${path}.city` })}</div>${select({ id: 'club-stadium', label: 'Estádio', value: club.stadiumId || '', property: 'stadiumId', optional: true, path: `${path}.stadiumId`, options: [{ value: '', label: 'Sem estádio vinculado' }, ...(document.stadiums || []).map(stadium => ({ value: stadium.id, label: `${stadium.name} · ${stadium.city}` }))], hint: 'O vínculo de cadastro não altera o estádio 3D da partida.' })}`;
}

export function clubSimulationFields(club, document, path) {
  if (!hasHistory(document)) return '';
  const number = (property, label, max, hint = '') => field({ id: `club-${property}`, label, value: club[property], property, optional: true, type: 'number', min: 0, max, path: `${path}.${property}`, hint });
  return `<div class="section-label section-separated"><h3>Parâmetros de simulação</h3><p>Os valores iniciam a gestão simplificada de novas carreiras; saves existentes conservam sua base. Reputação, torcida e patrocínio continuam descritivos. Estes parâmetros não representam valores oficiais sem pesquisa.</p></div><div class="form-grid">${number('reputation', 'Reputação', 100, 'De 0 a 100. Vazio significa não informado.')}${number('supporterCount', 'Tamanho da torcida', 2147483647, 'Quantidade inteira; não é uma contagem validada pelo editor.')}${field({ id: 'club-currency', label: 'Moeda dos orçamentos', value: club.currency, property: 'currency', optional: true, maxLength: 3, path: `${path}.currency`, hint: 'Código ISO com três letras maiúsculas. A carreira usa BRL quando não informado.' })}${field({ id: 'club-sponsorship', label: 'Patrocínio', value: club.sponsorship, property: 'sponsorship', optional: true, maxLength: 200, path: `${path}.sponsorship`, hint: 'Descrição livre; não é um contrato financeiro.' })}${number('transferBudget', 'Orçamento de transferências', 2147483647, 'Usado como caixa inicial da carreira. Sem valor: simulação inicia com 5.000.000. Zero é respeitado.')}${number('monthlyWageBudget', 'Orçamento salarial mensal', 2147483647, 'Usado como custo mensal da carreira. Sem valor: simulação usa 250.000 por mês. Zero é respeitado.')}</div>${notesField(club, 'club', path)}`;
}

const footer = (record, noun, explanation) => `<div class="detail-footer"><details class="record-id"><summary>Identificador permanente</summary><code>${e(record.id || record.code)}</code><p>${e(explanation)}</p></details><button class="button button-ghost-danger" id="delete-record">Excluir ${noun}</button></div>`;

export function stadiumForm(stadium, document) {
  const path = `stadiums[${document.stadiums.indexOf(stadium)}]`;
  const clubs = document.clubs.filter(club => club.stadiumId === stadium.id);
  return `<div class="detail-heading"><div><p class="eyebrow">FICHA DO ESTÁDIO</p><h2 id="detail-title" tabindex="-1">${e(stadium.name || 'Estádio sem nome')}</h2><p class="detail-subtitle">${e(stadium.city)} · ${e(countryName(document, stadium.countryCode))}</p></div><span class="record-symbol" aria-hidden="true">◎</span></div><form id="record-form" novalidate><fieldset id="record-fields"><legend class="sr-only">Editar estádio</legend><div class="section-label"><h3>Identificação e localização</h3><p>Um mesmo estádio pode ser vinculado a mais de um clube.</p></div>${field({ id: 'stadium-name', label: 'Nome do estádio', value: stadium.name, property: 'name', maxLength: 100, path: `${path}.name` })}<div class="form-grid">${countryField(document, { id: 'stadium-country', value: stadium.countryCode, path: `${path}.countryCode` })}${field({ id: 'stadium-city', label: 'Cidade', value: stadium.city, property: 'city', maxLength: 100, path: `${path}.city` })}</div>${field({ id: 'stadium-capacity', label: 'Capacidade', value: stadium.capacity, property: 'capacity', optional: true, type: 'number', min: 1, max: 1000000, path: `${path}.capacity`, hint: 'Deixe vazio se a capacidade ainda não foi confirmada.' })}<div class="notice"><strong>${clubs.length} ${clubs.length === 1 ? 'clube vinculado' : 'clubes vinculados'}</strong><p>${e(clubs.map(club => club.name).join(', ') || 'Escolha este estádio na ficha de um clube para criar o vínculo.')}</p></div><p class="form-note">Este é um cadastro esportivo. O cenário, a capacidade visual e a aparência do estádio 3D continuam definidos no Unity.</p></fieldset></form>${footer(stadium, 'estádio', 'O identificador preserva os vínculos dos clubes ao renomear o estádio.')}`;
}

export function countryForm(country, document) {
  const path = `countries[${document.countries.indexOf(country)}]`;
  return `<div class="detail-heading"><div><p class="eyebrow">FICHA DO PAÍS</p><h2 id="detail-title" tabindex="-1">${e(country.name || 'País sem nome')}</h2><p class="detail-subtitle">Código ${e(country.code)}</p></div><span class="record-symbol" aria-hidden="true">${e(country.code)}</span></div><form id="record-form" novalidate><fieldset id="record-fields"><legend class="sr-only">Editar país</legend><div class="form-grid">${field({ id: 'country-name', label: 'Nome do país', value: country.name, property: 'name', maxLength: 100, path: `${path}.name` })}${field({ id: 'country-code', label: 'Código do país', value: country.code, readOnly: true, path: `${path}.code`, hint: 'Duas letras maiúsculas. O código é a identidade e não muda ao renomear.' })}</div><div class="notice"><strong>Referência compartilhada</strong><p>Clubes, estádios e nacionalidades usam este cadastro. Para removê-lo, transfira primeiro todos os vínculos para outro país.</p></div></fieldset></form>${footer(country, 'país', 'Use o código ISO de duas letras ao cadastrar um país.')}`;
}

export function snapshotForm(document) {
  const snapshot = document.snapshot;
  return `<div class="detail-heading"><div><p class="eyebrow">CONTEXTO E PESQUISA</p><h2 id="detail-title" tabindex="-1">Referência da base</h2><p class="detail-subtitle">O período e as fontes acompanham a base exportada.</p></div></div><form id="record-form" novalidate><fieldset id="record-fields"><legend class="sr-only">Editar referência histórica</legend><div class="section-label"><h3>Retrato histórico</h3><p>Esta data descreve o conteúdo cadastrado. Alterá-la não transfere jogadores nem resolve automaticamente uma temporada histórica.</p></div><div class="form-grid">${field({ id: 'snapshot-label', label: 'Título da referência', value: snapshot.label, property: 'label', maxLength: 100, path: 'snapshot.label' })}${field({ id: 'snapshot-date', label: 'Data de referência', value: snapshot.date, property: 'date', maxLength: 10, path: 'snapshot.date', hint: 'AAAA-MM-DD. A data deve ser sustentada pelas fontes.' })}</div>${select({ id: 'snapshot-scope', label: 'Alcance dos elencos', value: snapshot.rosterScope, property: 'rosterScope', path: 'snapshot.rosterScope', options: [{ value: 'matchday-squads', label: 'Relacionados para partidas' }, { value: 'full-squads', label: 'Elencos completos' }], hint: 'Relacionados para partidas não representam necessariamente todos os atletas de um clube.' })}${textarea({ id: 'snapshot-notes', label: 'Contexto e limitações da pesquisa', value: snapshot.notes, property: 'notes', path: 'snapshot.notes', hint: 'Registre o que foi conferido, o que falta e quaisquer ressalvas de cobertura.' })}<div class="section-label section-separated"><h3>Fontes da pesquisa</h3><p>Mantenha ao menos uma fonte. Os links são referências; o editor não valida a veracidade do conteúdo.</p></div><div class="source-list">${snapshot.sources.map((source, index) => `<section class="source-entry" aria-label="Fonte ${index + 1}"><div class="source-heading"><h4>Fonte ${index + 1}</h4><button type="button" class="button button-ghost-danger" data-remove-source="${e(source.id)}">Remover fonte</button></div>${field({ id: `source-title-${index}`, label: 'Título da fonte', value: source.title, property: 'title', sourceId: source.id, maxLength: 200, path: `snapshot.sources[${index}].title` })}${field({ id: `source-url-${index}`, label: 'Endereço da fonte', value: source.url, property: 'url', sourceId: source.id, type: 'url', maxLength: 2048, path: `snapshot.sources[${index}].url`, hint: 'Endereço completo, começando com https:// ou http://.' })}</section>`).join('')}</div><button type="button" class="button button-outline" id="add-source">Adicionar fonte</button><p class="form-note">Revisão e identidade da base são preservadas. Salvar publica todas as edições deste rascunho em uma nova revisão.</p></fieldset></form>`;
}
